const fs = require('fs');
const path = require('path');
const { parse } = require('csv-parse/sync');

const csvPath = path.resolve(__dirname, '../data/processed/assist_articulations.csv');
const outPath = path.resolve(__dirname, '../app/data/assistArticulations.ts');

function generateAliases(courseCode) {
  const aliases = [courseCode, courseCode.replace(/\s+/g, '')];
  const parts = courseCode.split(/\s+/);

  if (parts.length === 2) {
    const [subject, number] = parts;
    aliases.push(`${subject} ${number}`);
    aliases.push(`${subject}${number}`);
    if (/^\d+$/.test(number)) {
      aliases.push(`${subject} ${Number(number)}`);
    }
  }

  return [...new Set(aliases)];
}

function splitCourseSet(courseSet) {
  if (!courseSet || /No Course Articulated/i.test(courseSet)) return [];

  return courseSet
    .split(/\s+OR\s+/i)
    .map((option) =>
      option
        .split(/\s+AND\s+|\s*\+\s*|\s*;\s*/i)
        .map((course) => course.trim())
        .filter(Boolean)
    )
    .filter((option) => option.length > 0);
}

function buildOptions(database) {
  const colleges = Object.keys(database).sort((a, b) => a.localeCompare(b));
  const targetsByCollege = {};
  const majorsByCollegeAndTarget = {};

  for (const college of colleges) {
    const targets = Object.keys(database[college] ?? {}).sort((a, b) =>
      a.localeCompare(b)
    );
    targetsByCollege[college] = targets;
    majorsByCollegeAndTarget[college] = {};

    for (const target of targets) {
      majorsByCollegeAndTarget[college][target] = Object.keys(
        database[college]?.[target] ?? {}
      ).sort((a, b) => a.localeCompare(b));
    }
  }

  return { colleges, targetsByCollege, majorsByCollegeAndTarget };
}

const records = parse(fs.readFileSync(csvPath, 'utf8'), {
  columns: true,
  skip_empty_lines: true,
  trim: true,
});

const grouped = {};

for (const record of records) {
  const {
    source_college,
    target_university,
    major,
    required_uc_course_or_area,
    articulated_ccsf_course,
  } = record;

  if (!source_college || !target_university || !major || !required_uc_course_or_area) {
    continue;
  }

  grouped[source_college] ??= {};
  grouped[source_college][target_university] ??= {};
  grouped[source_college][target_university][major] ??= [];
  grouped[source_college][target_university][major].push(record);
}

const requirements = {};

for (const [sourceCollege, targets] of Object.entries(grouped).sort(([a], [b]) =>
  a.localeCompare(b)
)) {
  requirements[sourceCollege] = {};

  for (const [targetUniversity, majors] of Object.entries(targets).sort(([a], [b]) =>
    a.localeCompare(b)
  )) {
    requirements[sourceCollege][targetUniversity] = {};

    for (const [major, articulations] of Object.entries(majors).sort(([a], [b]) =>
      a.localeCompare(b)
    )) {
      requirements[sourceCollege][targetUniversity][major] = {
        notes: `Articulation agreements from ASSIST.org for ${sourceCollege} to ${targetUniversity}. ${articulations.length} course mappings found.`,
        competitivenessNote: 'Transfer preparation based on official articulation agreements.',
        requiredCourses: articulations.map((articulation) => ({
          code: articulation.required_uc_course_or_area,
          name: articulation.required_uc_course_or_area,
          category: 'Major Requirement',
          priority: 'High',
          aliases: generateAliases(articulation.required_uc_course_or_area),
          satisfiedBy: splitCourseSet(articulation.articulated_ccsf_course),
        })),
      };
    }
  }
}

const options = buildOptions(requirements);
const output = `// Generated by scripts/generate_assist_articulations_static.js from data/processed/assist_articulations.csv.
// Do not edit this file by hand.

export const assistRequirements = ${JSON.stringify(requirements, null, 2)};

export const assistOptions = ${JSON.stringify(options, null, 2)};
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, output);

console.log(`Wrote ${outPath}`);
console.log(`Colleges: ${options.colleges.length}`);
console.log(`UC Berkeley majors: ${options.majorsByCollegeAndTarget.CCSF?.['UC Berkeley']?.length ?? 0}`);
